### PR TITLE
Issue #17 type system

### PR DESCRIPTION
**Pull request by dcrissman**
There are some big changes in this PR.

Highlights:
* entitymetadata is now being used to translate json to an ldap Entry.
* Created generic TranslatorFromJson with the hope that it possibly be moved to core and reused
* Created EntryBuilder as an implementation of TranslatorFromJson for Ldap
* Created integration tests to ensure date and binary types work properly
* Abstracted some of the CRUDController test code which could possibly be promoted to core.test and reused

### CODE REVIEW

**Comment by bserdar** [comment]
Even though object fields are not yet supported, when they are, the translation will use the translation for SimpleField. That one uses field.getName(), which is the latest element in the Path. Change that to field.getFullPath().toString(). EntryBuilder#75

Translation of a ReferenceField is identical to translation of an
ArrayField. During CRUD operations, you'll deal with
ResolvedReferenceFields, and that extends ArrayField.

Instead of throwing exceptions, you should build Error lists, and return those errors in the operation context. If an exception is related to one document, the error should be related to that document as well. There are exceptions in EntryBuilder, ResultTranslator.

**Comment by dcrissman** [comment]
Created #30 to address changes to support object fields and object array fields.

**Comment by dcrissman** [comment]
@bserdar This is ready for another CR. I believe your above concerns have been addressed or spun off into another issue.

**Comment by bserdar** [comment]
Do you have a separate PR for this, or do you want another review of the
complete source tree?

**Comment by dcrissman** [comment]
This was never merged, so I just used the same PR.

**Comment by bserdar** [comment]
EntryBuilder#121: would this need an LDAP translation for things like Date? Are you sure toString() would do?

**Comment by bserdar** [comment]
Same question goes for SimpleFieldTranslation: is there a need for LDAP translation for Date? 

Also, SimpleFieldTranslation and ArrayTransltion can share some of the code.

**Comment by dcrissman** [comment]
I created ITCaseLdapCRUDController_DataType_Test to ensure that date and binary field types worked as expected. Entry#addAttribute doesn't even have a version that accepts a proper Date object, so it is expecting a String representation. All that said, this is certainly something to watch when it is connected to a real LDAP server.

**Pull request merged**
