### PR TITLE
Issue31 field to attribute mapping

### PR DESCRIPTION
**Pull request by dcrissman**
Adds the ability to add give fields different names then their paired attribute.

### CODE REVIEW

**Comment by dcrissman** [comment]
Ready for review

**Comment by bserdar** [comment]
LdapMetadataProperty.translateFieldName should get a Path
translateAttributeName should return a Path

EntryBuilder: 
should be:
property.translateFieldName(field.getFullPath()

Does this support object arrays? If it does, how does it handle nested arrays.

NullLdapMetadataPropertyImpl makes it sound like it returns null. Call it Default* or Identity* (for it being an identity transformation)


FilterTranslator:

When you're translating a query, queyrExpression.getField() does *not* give you the full field name. Depending on the query and where certain expressions are evaluated from, there can be prefixes to that field name (i.e. if it is under an array query expression). Use QueryIterator instead of manually recursing down the query expression.


Rename FieldtoAttribute. Call if FieldAttrMapping or something. 
Are those equals() and hashcode() autoGenerated? They're bigger than the class itself.

There is no need for LdapMetadataPropertyImpl to be set-based. In fact, it could simply be a HashMap mapping fields to attrs, so you can prevent mapping a single field to two different attrs, or vice versa (using 2 hash maps). With set, you prevent the harmless duplicate identical mappings, but miss the erroneous 1-n mappings.

**Comment by dcrissman** [comment]
* NullLdapMetadataPropertyImpl and FieldtoAttribute have both been renamed.
* #41 was spun off to address using the QueryIterator.
* Objects and ObjectArrays are not currently supported, but #30 exists to add support in.
* equals() and hashcode() are indeed autogenerated and used to ensure uniqueness in the Set you mentioned

**Comment by dcrissman** [comment]
Created #42 to address using Path over String fieldNames.

**Comment by dcrissman** [comment]
@bserdar I believe I had address your concerns. I will fix the Path and QueryIterator issues in separate issues.

**Comment by dcrissman** [comment]
Ready for review

**Pull request merged**
