### PR TITLE
Fixes #40 use query iterator

### LINKED ISSUE #40: Handle new query types once core #297 is merged
Once https://github.com/lightblue-platform/lightblue-core/pull/297 is merged, the back-end code should handle the new query types: NaryValueRelationalExpression and NaryFieldRelationalExpression instead of NaryRelationalExpression. One way to make sure the code remains aware of the changes is to make sure you use QueryIterator when processing queries, instead of manually descending the query tree.

### PR DESCRIPTION
**Pull request by dcrissman**

### CODE REVIEW

**Comment by dcrissman** [comment]
This also fixes the fact that right now the ldap build is broken because of some changes in lightblue-core.

**Comment by dcrissman** [comment]
Not sure what is up with coveralls, but travis passed. This is ready for review.

**Comment by bserdar** [comment]
+ filters.add(iterate(subQuery)); //TODO Path?

Do this instead:

+ filters.add(iterate(subQuery, path));

**Comment by dcrissman** [comment]
I guess my question there is should I be modifying the Path for any subqueries or do I even need a Path at all? I am not actually using Path anywhere, and the FilterBuilder.build is the only consumer of  the new QueryIteratorSkeleton meaning that it will always be Path.EMPTY. So is there even any point to calling iterate(subQuery, path), when I could just call iterate(subQuery)?

I am passing Path alone in itrUnaryLogicalExpression, but if the answer to the above is 'no', then I would drop passing the Path here as well. Otherwise, I have no issue making the change you suggest.

**Comment by bserdar** [comment]
Pass Path during recursion. The only way path could change is through the
unsupported array queries.  If somehow we start supporting them, you'd need
Path passed down.

**Pull request merged**
