### PR TITLE
Travis update

### PR DESCRIPTION
**Pull request by luan-cestari**
The project is now following the same configuration as the https://github.com/lightblue-platform/lightblue-rest (but with a different encrypted key/pass to deploy to remote repository).

### CODE REVIEW

**Comment by dcrissman** [comment]
what are all these files for?

lightblue-ldap is not currently using arquillian.
sonar,sh and settings.xml are already on the root path.

**Comment by luan-cestari** [comment]
@dcrissman Probably it doesnt need all them, some are for arquillian which we can remove (but my first thought it would be easier to maintain keeping for all projects as they might need in the future). The other one give us a better log during critical errors (like the ones we got in rest repository), also, it provide a more sophisticate maven build using maven goals that will not put any jar in the local or remote repository until it is working  (as we have some inter-dependencies that makes us need to run install goal, instead of verify , for example). We can also remove the duplicated files in the root path

**Comment by dcrissman** [comment]
I modelled the placement of sonar/settings from lightblue-core. That said, ldap is missing the release.sh. Should we just put that in the root like core? Or are we swtiching all repos to use the etc directory?

**Comment by luan-cestari** [comment]
@dcrissman It will be switched , @jewzaam and I already started it. But, as you said earlier, some files are unnecessary, I'm merging the @jewzaam 's PRs related to this and then refactoring the PRs (like this one) to fix the last things around these changes.

**Comment by dcrissman** [comment]
I re-ran travis, but it is still failing. @luan-cestari any ideas?

**Comment by dcrissman** [comment]
This failure may have something to do with the fact that I used the coveralls-maven-plugin version 3.0.1 as opposed to version 2.2.0 that the other lightblue modules use. It appears that the goal was changed from 'cobertura' to 'report'.

https://github.com/trautonen/coveralls-maven-plugin/commit/195ddc4fbbdc2dc37d1fa74ac8885cb86060bb92

**Comment by dcrissman** [comment]
Fixing this will likely also resolve #13

**Comment by dcrissman** [comment]
@luan-cestari I created PR #37 which should fix this issue.

**Pull request merged**
